translating lesson1 section1 to pt-BR
Jmallone/buildspace-projects pull request #1
Opened 2021-12-25 23:23 UTC by Lorenzobattistela

I've been introduced to this repo right here https://github.com/web3brasil/web3brasil, and I saw that PT-BR translations were needed. So, I translated entirely the lesson 1 from section 1.

If anything wrong, just answer in comments! Congrats for the good work.

2021-12-26 16:38 UTC, Jmallone requested changes
Oie :D 
Obrigado por nos ajudar, isso vai ser muito importante, quanto mais pessoas souberem dessa tecnologia melhor.

Gostei bastante da tradução, só encontrei alguns erros de ortografia que acontece quando digitamos rápido e tentamos fazer a tradução simultânea rs isso acontece muito.

Solicitei algumas modificações, feito isso já dá para _mergear_ legal :+1:

2021-12-26 16:38 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_1_What_Is_A_NFT.md
> +Vamos passar por um examplo rapidamente.
Spellchecker: **examplo** -> *exemplo*

2021-12-26 16:38 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_1_What_Is_A_NFT.md
> +# Lesson_1_What_Is_A_NFT
Isso está no documento "template" em espanhol que o autor original fez, será que devemos deixar assim ou retirar?

2021-12-26 16:38 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_1_What_Is_A_NFT.md
> +Você precisa confiarm que o certificado da galeria será respeitado a longo termo, mas, no geral, isso é fáciL!
Spellchecker: 
- **confiarm** -> confirmar
- **fáciL** -> fácil.

2021-12-26 16:38 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_1_What_Is_A_NFT.md
> +Vamos dar uma olhada nesse examplo no **Mundo NFT** agora.
**examplo** -> exemplo

2021-12-26 16:38 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_2_Get_Local_Env_Running.md
> +Antes de qualquer coisa, vamos precisar colocar nossa rede local de Ethereum para funcionar. É dessa maneira que vamos poder compilar e testar nosso código de contratos inteligentes! Você sabe como é
Talvez trocar o pra para para rs
**"... um ambiente local pra trabalhar?"** -> "... um ambiente local para trabalhar?"

2021-12-26 16:38 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_2_Get_Local_Env_Running.md
> +2 -- Nosso contrato inteligente será implamntado na blockchain. Dessa maneira, qualquer pessoa no mundo terá acesso e poderá usar nosso contrato inteligente - e vamos deixar eles "mintarem" NFTs!
**implamntado** -> implementado/Implantado

2021-12-26 16:38 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_2_Get_Local_Env_Running.md
> +Você também vai querer instalar algo chamado **OpenZeppelin**, que é uma outra livaria muito usada para desenvolver contratos inteligentes seguros. Nós vamos aprender mais sobre isso depois. Por agor
**livaria** -> library
Pode colocar em inglês mesmo

2021-12-26 16:38 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_3_Mint_A_NFT_Locally.md
> +Nós vamos esperar até que o nosso contrato esteja oficialmente minerado e implamntado na nossa blockchain local! Exatamente, hardhat cria "mineradores" falsos na nossa máquina para tentar imitar da m
**implamntado** -> implementado ou implantado

2021-12-26 21:57 UTC, Lorenzobattistela commented on NFT_Collection/pt-br/Section_1/Lesson_1_What_Is_A_NFT.md
> +Você precisa confiarm que o certificado da galeria será respeitado a longo termo, mas, no geral, isso é fáciL!
Realmente, digitar rápido é complicado as vezes!

2021-12-26 21:58 UTC, Lorenzobattistela commented on NFT_Collection/pt-br/Section_1/Lesson_1_What_Is_A_NFT.md
> +# Lesson_1_What_Is_A_NFT
Eu acho legal deixar, pois dá uma referência se alguém quiser ver o original, talvez colocar a tradução do título embaixo?
Também é bom deixar pra padronizar os templates do ptbr e espanhol.

2021-12-26 21:59 UTC, Lorenzobattistela commented on NFT_Collection/pt-br/Section_1/Lesson_2_Get_Local_Env_Running.md
> +Antes de qualquer coisa, vamos precisar colocar nossa rede local de Ethereum para funcionar. É dessa maneira que vamos poder compilar e testar nosso código de contratos inteligentes! Você sabe como é
Com certeza, mais formal.

2021-12-26 22:04 UTC, Lorenzobattistela reviewed
I believe what your review speak to itself. Some spellcheck errors corrected, and about the title, I guess it's not a big deal, but we can leave without it because the name is already on the file, maybe translate it to PTBR too. But I think deleting it is the right choice.

2021-12-27 13:30 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_1_What_Is_A_NFT.md
> +# Lesson_1_What_Is_A_NFT
Talvez somente deixar por enquanto já é o suficiente, um otimo trabalho :D

2021-12-28 00:31 UTC, Jmallone commented
Para mim parece que está tudo Okay :) 

Parabens pela tradução

2021-12-28 00:31 UTC, merged