Translating section 1 lesson 4 to PTBR
Jmallone/buildspace-projects pull request #2
Opened 2021-12-28 01:43 UTC by Lorenzobattistela

I've just translated the last session 1 lesson. I have a doubt: what do you think of writing down credits for translating it? Maybe something like: Translation to PTBR by Lorenzo Battistela and Jmallone, what do you think?

2021-12-28 17:09 UTC, Jmallone requested changes
It's interesting writing our names, maybe in a **README.md** file inside the `NFT_Collection/pt-br `folder, what do you think? 

I wrote down some wrong words, done that the PR will be accepted :)

2021-12-28 17:09 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +Quando implementarmos nosso contrato,  nós preciamos falar  **para todos esses** mineradores, "ei, esse é um contrato inteligente novo, por favor adicione meu contrato inteligente à blockchain e diga
**preciamos** -> precisamos

2021-12-28 17:09 UTC, Jmallone commented on NFT_Collection/pt-br/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +Por quê você precisa dessa chave privada? Porque para perfomar uma transação como fazer deploy de um contrato, você precisa "logar" na blockchain e assinar/ fazer deploy do contrato. E, o seu nome de
**perfomar** - > performar

2021-12-28 17:09 UTC, Jmallone commented on NFT_Collection/pt-br/Section_2/Lesson_1_What_Is_On_Chain_Data.md
> +Mas, assumindo que a blockchain não caia, nossa NFT vai estar ali pra sempre! Isso é bem atraente, porque também significa que se você vender uma NFT, o comprador pode estar confiante que ela não vai
**pra** -> para

2021-12-28 17:09 UTC, Jmallone commented on NFT_Collection/pt-br/Section_2/Lesson_1_What_Is_On_Chain_Data.md
> +Por exemplo, aqui está um exemplo simples de SVG que renderiza uma caixa prete com algum texto branco no meio.
**prete** -> preta

2021-12-28 17:09 UTC, Jmallone commented on NFT_Collection/pt-br/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +Depois, precisamos de algum jeito pegear os dados das nossas NFT sem hospedar em algum lugar como o imgur (que pode cair ou morrer a qualquer momento!). Vá até [esse](https://www.utilities-online.inf
pegear -> pegar

2021-12-28 17:09 UTC, Jmallone commented on NFT_Collection/pt-br/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +Então, eu mudei um pouco para nossas NFTs de três palavras :). Mesma coisa! Um nome, descrição e imagem. Mas agora, aoa invés de apontar para um link imgur, vamos apontar pra nossa string codificada
**aoa** -> ao
**pra** -> para

2021-12-28 22:58 UTC, Lorenzobattistela commented
> It's interesting writing our names, maybe in a **README.md** file inside the `NFT_Collection/pt-br `folder, what do you think?
> 
> I wrote down some wrong words, done that the PR will be accepted :)


Yeah, I guess a README would be a good way, we can build a PR pattern too for contributions and also give credit for contributors.

2021-12-29 01:25 UTC, Jmallone approved these changes
Okay i will create a README.md or CONTRIBUTORS.md later

Already fine to me, :) +1 PR complete

2021-12-29 01:26 UTC, merged

2021-12-29 21:46 UTC, Lorenzobattistela commented
> Okay i will create a README.md or CONTRIBUTORS.md later
> 
> Already fine to me, :) +1 PR complete

Maybe update the contributors file? IDK if you pretend to make a PR for the main repo, but anyway, i've just saw that that is a contributors file.